---
driver:
  name: docker
  socket: tcp://127.0.0.1:2375

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
    driver_config:
      image: centos:centos6

suites:
  - name: default
    run_list: 
      - recipe[fuelphp]
    attributes:
      fuelphp:
        user: kitchen
      chef_client:
        config:
          ssl_verify_mode: ":verify_peer"
