---
driver:
  name: docker
  socket: tcp://127.0.0.1:4243

provisioner:
  name: chef_solo

platforms:
  - name: centos

suites:
  - name: default
    run_list: 
      - recipe[fuelphp]
    attributes:
      fuelphp:
        user: kitchen
      chef_client:
        config:
          ssl_verify_mode: ":verify_peer"
