---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
    driver_config:
      image: centos:centos6
  - name: centos-7.0
    driver_config:
      image: 2k0ri/centos7-systemd
      privileged: true
      run_command: /sbin/init

suites:
  - name: default
    run_list: 
      - recipe[fuelphp]
    attributes:
      fuelphp:
        user: kitchen
      chef_client:
        config:
          ssl_verify_mode: ":verify_peer"
